"""Conservative caps for v2 execution. Named so call sites do not use magic numbers."""

MAX_YAML_ALIASES = 32
MAX_YAML_BYTES = 256_000
MAX_SOURCE_FILES = 40
MAX_SOURCE_FILE_BYTES = 200_000
MAX_PROMPT_CHARS = 120_000
MAX_OUTPUT_BYTES = 64_000
MAX_GENERATED_FILE_BYTES = 100_000
MAX_ARTIFACT_PREVIEW_CHARS = 2_000
MAX_MUTANTS_DEFAULT = 100
MAX_EXAMPLES_DEFAULT = 100
MAX_BEHAVIOR_INPUTS_DEFAULT = 50
MAX_WORKERS_ALPHA = 1
PROCESS_KILL_GRACE_SECONDS = 0.5
DEFAULT_OPTIONAL_TIMEOUT_SECONDS = 900
DEFAULT_V1_TIMEOUT_SECONDS = 600
DEFAULT_TIMEOUT_SECONDS = DEFAULT_V1_TIMEOUT_SECONDS
DEFAULT_REQUIREMENTS_TIMEOUT_SECONDS = 90
DEFAULT_GENERATION_COMPILE_TIMEOUT_SECONDS = 10
DEFAULT_GENERATION_EXEC_TIMEOUT_SECONDS = 180
DEFAULT_MUTATION_TIMEOUT_SECONDS = 600
DEFAULT_BEHAVIOR_TIMEOUT_SECONDS = 180
DEFAULT_GENERATION_DEADLINE_MS = 200
DEFAULT_GENERATION_SEED = 0
MUTANT_TIMEOUT_FLOOR_SECONDS = 10
MUTANT_TIMEOUT_CEILING_SECONDS = 60
